# Consolidando vários arquivos .xlsx em um único DataFrame

##### OBSERVAÇÕES:

Ao setar o path dos arquivos é preciso ter prévio conhecimento das bases para que se consolide de forma correta e se há extenções diferente de planilha. 

**Exemplo: .xlsb

In [3]:
#importando bibliotecas
import os
import pandas as pd

#path - onde estão os arquivos
caminho = 'C:/Users/Lenovo/Desktop/BASE_DADOS/Python/'

In [8]:
#criando lista vazia para ser populada
df = []

#looping para obter as pastas na memória
for file in os.listdir(caminho): #lendo a pasta pelo diretório
    if file.endswith('.xlsx'):   #filtrando extensão
        df.append(pd.read_excel(os.path.join(caminho, file))) #concatenando caminho
      
print(len(df)) #retorna a quantidade de arquivos dentro da pasta e que será consolidada

df_principal = pd.concat(df, axis=0)

#visualizando dataframe
display(df_principal)

3

  LETRA  NUMERO
0     A       2
1     B       9
2     C       2
3     D       6
4     E      10
0     F       8
1     G       5
2     H       4
3     D       2
4     E       2
0     I       3
1     J       7
2     K       8
3     L       8
4     E      10